version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-category-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: category_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
      --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql_data:/var/lib/mysql
